[sharepoint]
username = "dussand.hurtado@kashio.net"
password = "Silvana1505$"

[notion]
notion_token = 'ntn_R78813053163bAeQ0L85HAKKZZTqTkhCFXNGFwsdTlD1Ev'
database_id = '21b1d5c32ce4801ebdf5f2b18186e21f'
